create database Practice;

use Practice;

CREATE TABLE SIMPLE (ROLL INT PRIMARY KEY,NAME VARCHAR(27), MARKS FLOAT, CITY VARCHAR(25));

INSERT INTO SIMPLE
(ROLL,NAME,MARKS,CITY)
VALUES 
(1,"POOJA", 61,"JAYSIINGPUR"),
(3,"SHAILENDRA", 67, "KAROLI-T"),
(7,"SHWETA",73.44,"KOLHAPUR"),
(59,"OMKAR",71.32,"PALUS");

SELECT * FROM SIMPLE;
SELECT NAME FROM SIMPLE;
SELECT DISTINCT(CITY) FROM SIMPLE;

CREATE TABLE CH_DATA(ROLL INT PRIMARY KEY,NAME VARCHAR(28),AGE INT CHECK (AGE>=18), MARKS FLOAT, GRADE VARCHAR(1), CITY VARCHAR(28) );
DROP TABLE CH_DATA;

INSERT INTO CH_DATA (ROLL, NAME, AGE, MARKS, GRADE, CITY)
VALUES (101, "ANIL", 24, 78, "C", "PUNE");

-- DATA IS NOT INSERTED THE AGE CONDITON NOT MSTCH-- 
INSERT INTO CH_DATA (ROLL, NAME, AGE, MARKS, GRADE, CITY)
VALUES
(102, "BHUMIKA", 17, 93, "A", "MUMBAI");

INSERT INTO CH_DATA (ROLL, NAME, AGE, MARKS, GRADE, CITY)
VALUES
(103, "CHETAN", 45, 85.55, "B", "MUMBAI");

-- DATA IS NOT INSERTED THE AGE CONDITON NOT MSTCH-- 
INSERT INTO CH_DATA (ROLL, NAME, AGE, MARKS, GRADE, CITY)
VALUES
(104, "DHRUV", 15, 96.33, "A", "DELHI");

INSERT INTO CH_DATA (ROLL, NAME, AGE, MARKS, GRADE, CITY)
VALUES
(105, "VIMAL", 65, 45.96, "D", "SANGLI");

INSERT INTO CH_DATA (ROLL, NAME, AGE, MARKS, GRADE, CITY)
VALUES
(106, "SHWETA",22, 94.65, "A", "KOLHAPUR");

SELECT * FROM CH_DATA;
SELECT DISTINCT(CITY) FROM CH_DATA;
SELECT NAME,ROLL FROM CH_DATA;